/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package students;
import java.util.Random;
/**
 * This is a class for storing the projects details
 * @author Abdullah Butt
 * @author 2020-CS-63
 */
public class Project {
    
    private String title;
    
    private String type;
    
    private String description;
    
    private String id;
    
    public Project()
    {}
    
    /**
     * This is a parameterized for the Project class
     * @param type Type of the project chosen by the committee member using combo box
     */
    public Project(String type)
    {
        this.type=type;
        setId();
    }
    
    /**
     * This is a setter for the id of the project that is going to be unique in each case and is 
     * going to be accessed using this unique id. Also the Advisor will be given the same id 
     */
    public void setId()
    {
        String first="Pro-";
        Random rand=new Random();
        int rnd=rand.nextInt(1001);
        first+=rnd;
        this.id=first;
    }

    /**
     * This is a getter for the title of the project
     * @return String containing the title of the particular project
     */
    public String getTitle() {
        return title;
    }

    /**
     * This is a getter for the type of the project
     * @return String containing the type of the particular project
     */
    public String getType() {
        return type;
    }

    /**
     * This is a getter for the description of the project
     * @return String containing the description of the particular project
     */
    public String getDescription() {
        return description;
    }

    /**
     * This is a getter for the description of the project that has been generated by the system
     * @return String containing the id of the particular project
     */
    public String getId() {
        return id;
    }
    
    /**
     * This is a setter for the title of the project
     * @param title String inputted by the member of the committee
     * @return Boolean showing whether the input is valid title or not
     */
    public boolean setTitle(String title)
    {
        boolean flag=false;
        int size=title.length();
        for(int i=0;i<size;i++)
        {
            if((title.charAt(i)>='A' && title.charAt(i)<='Z')||(title.charAt(i)>='a' && title.charAt(i)<='z')||(title.charAt(i)==' '))
            {
                flag=true;
            }
            else
                return false;
        }
        this.title=title;
        return flag;
    }
    
    /**
     * This is a setter for the description of the project
     * @param description String inputted from the user
     * @return Boolean telling whether the String is valid description or not
     */
    public boolean setDescription(String description)
    {
        boolean flag=false;
        int size=description.length();
        for(int i=0;i<size;i++)
        {
            if((description.charAt(i)>='A' && description.charAt(i)<='Z')||(description.charAt(i)<='\n')||(description.charAt(i)>='a' && description.charAt(i)<='z')||(description.charAt(i)>='0' && description.charAt(i)<='9')||(description.charAt(i)==' ')||(description.charAt(i)==',')||(description.charAt(i)=='.')||(description.charAt(i)=='(')||(description.charAt(i)==')')||(description.charAt(i)=='%'))
                flag=true;
            else
                return false;
        }
        this.description=description;
        return flag;
    }
//    only for file handling
    public void setId(String id)
    {
        this.id=id;
    }
    
//    only for file handling
    public void setType(String type)
    {
        this.type=type;
    }
    
}
